version: "3"
services:
  mysql_service:
    image: mysql:8.0.27
    environment:
      - MYSQL_DATABASE=nombre
      - MYSQL_ROOT_PASSWORD=claveroot
      - MYSQL_USER=miusuario
      - MYSQL_PASSWORD=mipassword
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    ports:
      - 23306:3306
   
  php_service:
    image: php:7-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./worki/:/var/www/html
    ports:
      - 8080:80
    links: 
      - mysql_service